apiVersion: v1
kind: harmonyhub-workflow
name: Groq
description: Groq
svg: >-
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
  fill="currentColor">
    <text x="12" y="12" text-anchor="middle" dominant-baseline="middle" font-size="10" font-weight="bold">
      Groq
    </text>
  </svg>
headers:
  Content-Type: application/json
  Authorization: Bearer AddYourTokenHere
variables:
  url: https://api.groq.com/openai/v1/chat/completions
  model: llama3-8b-8192
  question: what are language models?
workflow:
  steps:
    - id: '1'
      type: restapi
      name: Groq API Call
      http:
        method: POST
        url: $url
      data: |-
        {
          "model": "{{model}}",
          "messages": [{
              "role": "user",
              "content": "{{question}}"
          }]
        }
      outputs:
        llm_response: .response_body.choices[0].message.content
      prints:
        - $llm_response
