RestApiTool:
  id: 1
  type: restapi
  description: Rest API
  svg: |
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1">
        <path d="M16 13c-1.3 0-2.4.8-2.8 2H9c0-.7-.2-1.3-.5-1.8l7.1-7.3c.3 0 .6.1.9.1C17.9 6 19 4.9 19 3.5S17.9 1 16.5 1S14 2.1 14 3.5c0 .3.1.7.2 1l-7 7.2c-.6-.5-1.4-.7-2.2-.7V6.8C6.2 6.4 7 5.3 7 4c0-1.7-1.3-3-3-3S1 2.3 1 4c0 1.3.8 2.4 2 2.8v4.7c-1.2.7-2 2-2 3.4c0 2.2 1.8 4 4 4c1.5 0 2.8-.8 3.4-2h4.7c.4 1.1 1.5 2 2.8 2c1.6 0 3-1.3 3-3C19 14.3 17.6 13 16 13"/>
    </svg>
  category: Base
  properties:
    - name: Name
      field: name
      datatype: Text
      required: true
      hint: Enter Rest API Name
      value: Rest API
    - name: HTTP Method
      field: http.method
      datatype: Enumeration
      required: true
      options: [GET, OPTIONS, PUT, POST, PATCH, DELETE]
      hint: Enter HTTP Method GET, OPTIONS, PUT, POST, PATCH, DELETE
      value: GET
    - name: URL
      field: http.url
      datatype: Text
      required: true
      hint: Enter URL
      value: null
    - name: Headers
      field: headers
      datatype: Object
      required: false
      hint: Enter Headers {}
      value: {}
    - name: Data
      field: data
      datatype: TextLarge
      required: false
      hint: Enter PUT/POST/PATCH/DELETE data
      value: null
    - name: Outputs
      field: outputs 
      datatype: Object
      required: false
      hint: Enter Output {}
      value: {}
    - name: Prints
      field: prints
      datatype: Array
      required: false
      hint: Enter Print []
      value: []
    - name: Tests
      field: tests
      datatype: ArrayObject
      required: false
      hint: Enter Tests [{}]
      value: []

DatabaseTool:
  id: 2
  type: database
  description: Database
  svg: |
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1">
      <path d="M12 21q-3.775 0-6.387-1.162T3 17V7q0-1.65 2.638-2.825T12 3t6.363 1.175T21 7v10q0 1.675-2.613 2.838T12 21m0-11.975q2.225 0 4.475-.638T19 7.025q-.275-.725-2.512-1.375T12 5q-2.275 0-4.462.638T5 7.025q.35.75 2.538 1.375T12 9.025M12 14q1.05 0 2.025-.1t1.863-.288t1.675-.462T19 12.525v-3q-.65.35-1.437.625t-1.675.463t-1.863.287T12 11t-2.05-.1t-1.888-.288T6.4 10.15T5 9.525v3q.625.35 1.4.625t1.663.463t1.887.287T12 14m0 5q1.15 0 2.338-.175t2.187-.462t1.675-.65t.8-.738v-2.45q-.65.35-1.437.625t-1.675.463t-1.863.287T12 16t-2.05-.1t-1.888-.288T6.4 15.15T5 14.525V17q.125.375.788.725t1.662.638t2.2.462T12 19" />
    </svg>
  category: Base
  properties:
    - name: Name
      field: name
      datatype: Text
      required: true
      hint: Enter Data Name
      value: Database
    - name: DBType
      field: dbtype
      datatype: Enumeration
      required: true
      options: [oracle, mysql, postgresql, sqlite]
      hint: Enter Data Type oracle, mysql, postgresql, sqlite
      value: oracle
    - name: Host
      field: host
      datatype: Text
      required: true
      hint: Enter Host
      value: null
    - name: Port
      field: port
      datatype: Text
      required: true
      hint: Enter Port
      value: null
    - name: Database
      field: database
      datatype: Text
      required: true
      hint: Enter Database
      value: null
    - name: User
      field: user
      datatype: Text
      required: true
      hint: Enter User
      value: null
    - name: Password
      field: password
      datatype: Text
      required: true
      hint: Enter Password
      value: null
    - name: Query
      field: query
      datatype: TextLarge
      required: false
      hint: Enter Query
      value: null
    - name: Outputs
      field: outputs 
      datatype: Object
      required: false
      hint: Enter Output {}
      value: {}
    - name: Prints
      field: prints
      datatype: Array
      required: false
      hint: Enter Print []
      value: []
    - name: Tests
      field: tests
      datatype: ArrayObject
      required: false
      hint: Enter Tests [{}]
      value: []

DecisionTool:
  id: 3
  type: switch
  description: Decision
  svg: |
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="1" viewBox="0 0 24 24" >
      <path stroke-linecap="round" stroke-linejoin="round" d="M2.7 10.3a2.41 2.41 0 0 0 0 3.41l7.59 7.59a2.41 2.41 0 0 0 3.41 0l7.59-7.59a2.41 2.41 0 0 0 0-3.41L13.7 2.71a2.41 2.41 0 0 0-3.41 0Z" />
    </svg>
  category: Base
  properties:
    - name: Name
      field: name
      datatype: Text
      required: true
      hint: Enter Decision Name
      value: Decision

LoopTool:
  id: 4
  type: loop
  description: Loop
  svg: |
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="1" viewBox="0 0 24 24">
      <path d="M17.65 6.35A7.96 7.96 0 0 0 12 4a8 8 0 0 0-8 8a8 8 0 0 0 8 8c3.73 0 6.84-2.55 7.73-6h-2.08A5.99 5.99 0 0 1 12 18a6 6 0 0 1-6-6a6 6 0 0 1 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4z"/>
    </svg>
  category: Base
  properties:
    - name: Name
      field: name
      datatype: Text
      required: true
      hint: Enter Loop Name
      value: Loop

ErrorTool:
  id: 5
  type: errorhandler
  description: Error Handler
  svg: |
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="1" viewBox="0 0 24 24">
      <path d="M12 16.462q.262 0 .439-.177q.176-.177.176-.439q0-.261-.177-.438T12 15.23t-.438.177t-.177.438t.177.439t.438.177m-.5-3.308h1v-6h-1zM12.003 21q-1.866 0-3.51-.708q-1.643-.709-2.859-1.924t-1.925-2.856T3 12.003t.709-3.51Q4.417 6.85 5.63 5.634t2.857-1.925T11.997 3t3.51.709q1.643.708 2.859 1.922t1.925 2.857t.709 3.509t-.708 3.51t-1.924 2.859t-2.856 1.925t-3.509.709M12 20q3.35 0 5.675-2.325T20 12t-2.325-5.675T12 4T6.325 6.325T4 12t2.325 5.675T12 20m0-8" />
    </svg>
  category: Base
  properties:
    - name: Name
      field: name
      datatype: Text
      required: true
      hint: Enter Error Handler Name
      value: Error Handler