name: Publish Python Package

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Navigate to the Python CLI directory
        run: |
          cd python-cli
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Replace with your desired Python version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build distribution
        run: python setup.py sdist bdist_wheel
      - name: Publish to GitHub Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | tr -d '\n' > ~/.config/credentials
          python -m twine upload dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
